[package]
name = "ttserver"
version = "0.2.10"

edition = "2018"
authors = ["FanHui <fanhui.x@gmail.com>", "FanHui <hui.fan@mail.ru>"]
description = "Lightweight private cloud solution for SME scenarios."
license = "MIT OR Apache-2.0"
keywords = ["openstack", "k8s", "kvm", "cloud"]
categories = ["command-line-utilities"]
homepage = "https://github.com/ktmlm/TTstack"
repository = "https://github.com/ktmlm/TTstack.git"

[dependencies]
nix = "0.18"
clap = "2.33"
lazy_static = "1.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"

futures = { version = "0.3.5", features = ["thread-pool"] }
futures-timer = "3.0.2"

myutil = "0.2"
num_cpus = "1.13"
parking_lot = "0.11"

ttcore = { path = "../core", default-features = false }
ttserver_def = { path = "../server_def" }

[features]
default = [ "nft", "zfs" ]
cow = [ "ttcore/cow" ]
nft = [ "ttcore/nft" ]
zfs = [ "ttcore/zfs" ]
testmock = [ "ttcore/testmock" ]
