[package]
name = "ttcore"
version = "0.2.10"

edition = "2018"
authors = ["FanHui <fanhui.x@gmail.com>", "FanHui <hui.fan@mail.ru>"]
description = "Lightweight private cloud solution for SME scenarios."
license = "MIT OR Apache-2.0"
keywords = ["openstack", "k8s", "kvm", "cloud"]
categories = ["command-line-utilities"]
homepage = "https://github.com/ktmlm/TTstack"
repository = "https://github.com/ktmlm/TTstack.git"

[dependencies]
nix = "0.18"
libc = "0.2"
lazy_static = "1.4"
parking_lot = "0.11"
ttcore_def = { path = "../core_def", version = "0.2" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
myutil = "0.2"

futures = { version = "0.3.5", features = ["thread-pool"] }
futures-timer = "3.0.2"

[features]
default = [ "nft", "zfs" ]
cow = []
nft = []
zfs = []
testmock = []
