[package]
name = "tt"
version = "0.2.10"

edition = "2018"
authors = ["FanHui <fanhui.x@gmail.com>", "FanHui <hui.fan@mail.ru>"]
description = "Lightweight private cloud solution for SME scenarios."
license = "MIT OR Apache-2.0"
keywords = ["openstack", "k8s", "kvm", "cloud"]
categories = ["command-line-utilities"]
homepage = "https://github.com/ktmlm/TTstack"
repository = "https://github.com/ktmlm/TTstack.git"

[dependencies]
clap = "2.33"
lazy_static = "1.4"

nix = "0.18"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"

myutil = "0.2"
threadpool = "1.8"

ttserver_def = { path = "../server_def" }
ttrexec = { path = "../rexec", default-features = false, features = [ "client" ] }
